env = Environment()
env.Replace(
    CCFLAGS=['-Wall', '-O2', '-fPIC', '-m32'],
    CPPPATH=['/opt/intel/mkl/9.1/include'],
    LIBPATH=['/opt/intel/mkl/9.1/lib/32'],
    LIBS=['mkl', 'libguide'],
    LINKFLAGS=['-m32', '-Wl,-rpath,/opt/intel/mkl/9.1/lib/32'])
env.SharedLibrary('array4j', ['array4j.c'])
